version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: research-agent-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  research-agent:
    build: .
    container_name: research-agent-api
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./logs:/app/logs
      - model_cache:/app/models
    env_file:
      - .env
    restart: unless-stopped
    # GPU 지원이 필요한 경우 주석 해제
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

volumes:
  redis_data:
  model_cache: